//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeCoSwell.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_tri1 {
            get {
                return ((string)(this["tb_tri1"]));
            }
            set {
                this["tb_tri1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_tri2 {
            get {
                return ((string)(this["tb_tri2"]));
            }
            set {
                this["tb_tri2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_tri3 {
            get {
                return ((string)(this["tb_tri3"]));
            }
            set {
                this["tb_tri3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_tri4 {
            get {
                return ((string)(this["tb_tri4"]));
            }
            set {
                this["tb_tri4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_consigne {
            get {
                return ((string)(this["tb_consigne"]));
            }
            set {
                this["tb_consigne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("972")]
        public string tb_con_max {
            get {
                return ((string)(this["tb_con_max"]));
            }
            set {
                this["tb_con_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51")]
        public string tb_con_min {
            get {
                return ((string)(this["tb_con_min"]));
            }
            set {
                this["tb_con_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_freq_countmax {
            get {
                return ((string)(this["tb_freq_countmax"]));
            }
            set {
                this["tb_freq_countmax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string tb_freq_div {
            get {
                return ((string)(this["tb_freq_div"]));
            }
            set {
                this["tb_freq_div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1006")]
        public string tb_can10b_max {
            get {
                return ((string)(this["tb_can10b_max"]));
            }
            set {
                this["tb_can10b_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public string tb_can10b_min {
            get {
                return ((string)(this["tb_can10b_min"]));
            }
            set {
                this["tb_can10b_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_10b_can1 {
            get {
                return ((string)(this["tb_10b_can1"]));
            }
            set {
                this["tb_10b_can1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_10b_can2 {
            get {
                return ((string)(this["tb_10b_can2"]));
            }
            set {
                this["tb_10b_can2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_10b_can3 {
            get {
                return ((string)(this["tb_10b_can3"]));
            }
            set {
                this["tb_10b_can3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_10b_can4 {
            get {
                return ((string)(this["tb_10b_can4"]));
            }
            set {
                this["tb_10b_can4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_consigne1 {
            get {
                return ((string)(this["tb_consigne1"]));
            }
            set {
                this["tb_consigne1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_consigne2 {
            get {
                return ((string)(this["tb_consigne2"]));
            }
            set {
                this["tb_consigne2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_PID_cible2 {
            get {
                return ((string)(this["tb_PID_cible2"]));
            }
            set {
                this["tb_PID_cible2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_PID_cible1 {
            get {
                return ((string)(this["tb_PID_cible1"]));
            }
            set {
                this["tb_PID_cible1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tb_con_pour1Visible {
            get {
                return ((bool)(this["tb_con_pour1Visible"]));
            }
            set {
                this["tb_con_pour1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tb_con_max1Visible {
            get {
                return ((bool)(this["tb_con_max1Visible"]));
            }
            set {
                this["tb_con_max1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tb_con_min1Visible {
            get {
                return ((bool)(this["tb_con_min1Visible"]));
            }
            set {
                this["tb_con_min1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmb_consigne_CAN1Visible {
            get {
                return ((bool)(this["cmb_consigne_CAN1Visible"]));
            }
            set {
                this["cmb_consigne_CAN1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmb_consigne_CAN2Visible {
            get {
                return ((bool)(this["cmb_consigne_CAN2Visible"]));
            }
            set {
                this["cmb_consigne_CAN2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tb_con_max2Visible {
            get {
                return ((bool)(this["tb_con_max2Visible"]));
            }
            set {
                this["tb_con_max2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tb_consigne2Visible {
            get {
                return ((bool)(this["tb_consigne2Visible"]));
            }
            set {
                this["tb_consigne2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gb_ActB1Visible {
            get {
                return ((bool)(this["gb_ActB1Visible"]));
            }
            set {
                this["gb_ActB1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gb_ActB2Visible {
            get {
                return ((bool)(this["gb_ActB2Visible"]));
            }
            set {
                this["gb_ActB2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gb_ActB3Visible {
            get {
                return ((bool)(this["gb_ActB3Visible"]));
            }
            set {
                this["gb_ActB3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gb_ActB4Visible {
            get {
                return ((bool)(this["gb_ActB4Visible"]));
            }
            set {
                this["gb_ActB4Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmb_chx_cons_visible {
            get {
                return ((bool)(this["cmb_chx_cons_visible"]));
            }
            set {
                this["cmb_chx_cons_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gb_PID_visible {
            get {
                return ((bool)(this["gb_PID_visible"]));
            }
            set {
                this["gb_PID_visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string tb_div_sinus1 {
            get {
                return ((string)(this["tb_div_sinus1"]));
            }
            set {
                this["tb_div_sinus1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string tb_div_sinus2 {
            get {
                return ((string)(this["tb_div_sinus2"]));
            }
            set {
                this["tb_div_sinus2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_multinivmax1 {
            get {
                return ((string)(this["tb_multinivmax1"]));
            }
            set {
                this["tb_multinivmax1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_multinivmax2 {
            get {
                return ((string)(this["tb_multinivmax2"]));
            }
            set {
                this["tb_multinivmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_multinivmax3 {
            get {
                return ((string)(this["tb_multinivmax3"]));
            }
            set {
                this["tb_multinivmax3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_multinivmax4 {
            get {
                return ((string)(this["tb_multinivmax4"]));
            }
            set {
                this["tb_multinivmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string tb_multinivmin1 {
            get {
                return ((string)(this["tb_multinivmin1"]));
            }
            set {
                this["tb_multinivmin1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string tb_multinivmin2 {
            get {
                return ((string)(this["tb_multinivmin2"]));
            }
            set {
                this["tb_multinivmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string tb_multinivmin3 {
            get {
                return ((string)(this["tb_multinivmin3"]));
            }
            set {
                this["tb_multinivmin3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string tb_multinivmin4 {
            get {
                return ((string)(this["tb_multinivmin4"]));
            }
            set {
                this["tb_multinivmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_consigne3 {
            get {
                return ((string)(this["tb_consigne3"]));
            }
            set {
                this["tb_consigne3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("972")]
        public string tb_con_max2 {
            get {
                return ((string)(this["tb_con_max2"]));
            }
            set {
                this["tb_con_max2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51")]
        public string tb_con_min2 {
            get {
                return ((string)(this["tb_con_min2"]));
            }
            set {
                this["tb_con_min2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51")]
        public string tb_con_min3 {
            get {
                return ((string)(this["tb_con_min3"]));
            }
            set {
                this["tb_con_min3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("972")]
        public string tb_con_max3 {
            get {
                return ((string)(this["tb_con_max3"]));
            }
            set {
                this["tb_con_max3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tb_con_max3Visible {
            get {
                return ((bool)(this["tb_con_max3Visible"]));
            }
            set {
                this["tb_con_max3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tb_consigne3Visible {
            get {
                return ((bool)(this["tb_consigne3Visible"]));
            }
            set {
                this["tb_consigne3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string tb_div_sinus3 {
            get {
                return ((string)(this["tb_div_sinus3"]));
            }
            set {
                this["tb_div_sinus3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_PID_cible3 {
            get {
                return ((string)(this["tb_PID_cible3"]));
            }
            set {
                this["tb_PID_cible3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_offset1 {
            get {
                return ((string)(this["tb_offset1"]));
            }
            set {
                this["tb_offset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_amplitude1 {
            get {
                return ((string)(this["tb_amplitude1"]));
            }
            set {
                this["tb_amplitude1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool l_amplitude1visible {
            get {
                return ((bool)(this["l_amplitude1visible"]));
            }
            set {
                this["l_amplitude1visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_amplitude2 {
            get {
                return ((string)(this["tb_amplitude2"]));
            }
            set {
                this["tb_amplitude2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool l_amplitude2visible {
            get {
                return ((bool)(this["l_amplitude2visible"]));
            }
            set {
                this["l_amplitude2visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_offset2 {
            get {
                return ((string)(this["tb_offset2"]));
            }
            set {
                this["tb_offset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023")]
        public string tb_amplitude3 {
            get {
                return ((string)(this["tb_amplitude3"]));
            }
            set {
                this["tb_amplitude3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool l_amplitude3visible {
            get {
                return ((bool)(this["l_amplitude3visible"]));
            }
            set {
                this["l_amplitude3visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public string tb_offset3 {
            get {
                return ((string)(this["tb_offset3"]));
            }
            set {
                this["tb_offset3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cmb_consigne_CAN3 {
            get {
                return ((bool)(this["cmb_consigne_CAN3"]));
            }
            set {
                this["cmb_consigne_CAN3"] = value;
            }
        }
    }
}
